services:
  identity-svc:
    build:
      context: ./identity
      dockerfile: Dockerfile
    container_name: identity-svc
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__IdentityDb=${ConnectionStrings__IdentityDb}
    restart: unless-stopped

  resource-svc:
    build:
      context: ./resource
      dockerfile: Dockerfile
    container_name: resource-svc
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__ResourceDb=${ConnectionStrings__ResourceDb}
    restart: unless-stopped