name: Trigger auto deployment for resource-svc

# When this action will be executed
on:
  # Automatically trigger ONLY when changes are made inside the 'resource' folder
  push:
    branches: 
      - deploy/production
    paths:
      - 'resource/**'
      - '.github/workflows/resource-svc-AutoDeployTrigger-734199a2-3e86-4e3a-a0a0-7820f77e3b62.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write # Required for requesting the OIDC JWT Token
      contents: read  # Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.RESOURCESVC_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.RESOURCESVC_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.RESOURCESVC_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          # Tells Azure to build ONLY the resource folder:
          appSourcePath: ${{ github.workspace }}/resource
          registryUrl: bismarckregistry.azurecr.io
          registryUsername: ${{ secrets.RESOURCESVC_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.RESOURCESVC_REGISTRY_PASSWORD }}
          containerAppName: resource-svc
          resourceGroup: bismarck-pam-rg
          imageToBuild: bismarckregistry.azurecr.io/resource-svc:${{ github.sha }}